### ISSUE TITLE
Please add Switch Support.

### ISSUE THREAD

**Issue by RyuSeisuke1992** [mburbea/koar-item-editor#90]

**Comment by mburbea** [comment]
The switch version just came out today.
I don't own the game on switch, and I at this time do not plan on purchasing it.
Unfortunately, without having a copy of the game, debugging this can be very tricky :(

If you have the game and know about encryption and have access to some save files, that can help. Alternatively, you can help me get the game in a legal fashion. Otherwise, I am open to a PR for the switch support.

**Comment by RyuSeisuke1992** [comment]
Thank you. :)
